In [ ]:
## Dingyi Kang
## A20308046
## Assignment3 - problem 3

import numpy as np

In [ ]:
X = np.array([[7, 5, 0, 0, 3, 2],[6, 4, 5, 1, 4, 8],[9, 0, 2, 2, 5, 4],[6, 3, 4, 7, 9, 8],[5, 7, 5, 6, 9, 0],[7, 9, 0, 8, 2, 3]])
X.shape

(6, 6)

In [ ]:
f = np.array([[1, 0, -1],[2, 0, -2],[1, 0, -1]])
f.shape

(3, 3)

Answer to question 1:
The dimension of the input is 6 x 6 x 1. 
The dimension of the kernel is 3 x 3 x 1

There are 10 parameters in the kernel f. 
Namely, (3 * 3 * 1 + 1)*1 = 10

In [ ]:
# with stride of 1 by default, without padding
def convol(input, filter):
  # initialize a 4x4 array to store the computed values of activation map
  arr = np.zeros((4, 4))
  for r in range(4):
    for c in range(4):
      #get the 3 by 3 submatrix of the input which is center around one of the element in the center 4 by 4 submatrix of the input. The index of the center element of this current submatrix is at rth row and cth column.
      t = input[r:r+3,c:c+3]
      # do the inner product between this submatrix with filter
      ip = np.inner(t, filter)
      # the sum of the values of the main diagonal element in the output matrix is the target value of convoltion operation
      arr[r][c] = ip[0][0] + ip[1][1] + ip[2][2]
  return arr

In [ ]:
activationMap = convol(X, f)
print(activationMap)

[[ 16.   9.  -4. -18.]
 [ 17.  -5. -10. -12.]
 [ 11.  -9. -17.   2.]
 [  9.  -1. -15.  16.]]


Answer to question 2: the output activation map of applying the convolutional operation using the filter f on the input X without padding is shown as above

In [ ]:
# 2x2 filter with stride of 2
def maxPool(input):
  # initialize a 2x2 array to store the computed values
  arr = np.zeros((2, 2))
  for r in range(2):
    for c in range(2):
      # increment index of row and column by 2 instead of 1
      if c == 1:
        j = c + 1
      else:
        j = c
      if r == 1:
        i = r + 1
      else:
        i = r
      #get the 2 by 2 target submatrix of the input
      t = input[i:i+2,j:j+2]
      #get maximum value from the matrix and assign to our target return array
      arr[r][c] = t.max()
  return arr

In [ ]:
output = maxPool(activationMap)
print(output)

[[17. -4.]
 [11. 16.]]


Answer to question 3: the output matrix of applying a max-pooling operation on the output from the previous question is shown as above